### ISSUE TITLE
Discuss: "No matching calls" when verify() calls should diff...

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/mockito#14]
if there is an equivalent call with non-matching parameters. For example, instead of

```
No matching calls. All calls: MyService.update(div, {bottom: 5})
```

Perhaps

```
No matching calls.

FOUND: MyService.update(div, {bottom: 5})
EXPECTED: MyService.update(div, {bottom: 4})
DIFF:
  bottom was 4 instead of 5
```

(I'd be happy to help write this, just wanted input first)

@TedSander

**Comment by TedSander** [comment]
Hmm interesting. We may be able to do this because of the matcher interface has describeMismatch which with matchers that conform to the interface should give a pretty good description of the mismatch.

I think the difficulty is going to be in telling which call was the closest. If there are multiple calls on a mock object which do you display? Do you display the mismatch for all of them? That logic seems like it could get evil.

In the case below it isn't clear which value we should show as the miss match. Things get even crazier if you have two arguments that match the signature, but don't match the values. Then you have even more information to display to the user.

```dart
No matching calls. All calls: MyService.update(div, {bottom: 5}), MyService.update(div, {top: 6}), MyService.update(div, {bottom: 7})
```

**Comment by fibulwinter** [comment]
I would prefer to keep verification logic as simple and predictable as possible. So in general I'm again this change. 

At the same time I think that we can implement it for just one special case: there is one and only one unmatched call to the mock.

**Comment by Andersmholmgren** [comment]
+1 for this feature request. Would be super helpful

**Comment by matanlurey** [comment]
@TedSander: In the case of multiple matching calls, how is normally handled? E.g. if I expected

```dart
verify(update(div, bottom: 5))
```

But the calls are

```dart
update(div, bottom: 5);
update(div, bottom: 4);
update(div, bottom: 5);
```

My verify is valid, right?

---

@fibulwinter: Verification logic would stay the same... The output message would just be more helpful.

Case in point, I have some method calls with 6-7 parameters. If even one or two is off, it becomes a big hunting game to figure exactly what parameters were unexpected or what parameters were not provided.

---

I can send a PR with a proof of concept and go from there?

**Comment by TedSander** [comment]
Correct your verify would pass.

The case I was trying to point out is what if you wanted to verify
```dart
verify(update(div, bottom: 4.5))
```

What would the output be on a miss match? Do you pick one to do the diff on? Do you output the diff for each call?

A PR would be good. We can look at the code and see what we can do.

I agree with @fibulwinter that a single call will be easy enough. Multiple calls might be a lot of noise.

**Comment by matanlurey** [comment]
I think we can close this, given the lack of progress, even from myself :)
