### ISSUE TITLE
How to unit test the presenter in a mvp-design in flutter when it is dependent on the view?

### ISSUE THREAD

**Issue by analistacarlosh** [dart-lang/mockito#206]
Hello everyone,

I have the same question of this another friend:
https://stackoverflow.com/questions/56948372/how-to-unit-test-the-presenter-in-a-mvp-design-in-flutter-when-it-is-dependent-o

I have a LoginPresenter and I'm doing this test, but Mockito, can't find your identity `mockView.doLogin(user)` when the `await mockPresenter.login(user);` execute in a success flow. 

``` 
test('success', () async {
        User user = User(userMocked, "1234");
        when(mockManager.login(user))
            .thenAnswer((_) => SynchronousFuture(user));
        await mockPresenter.login(user);
        verify(mockView.doLogin(user));
      });
```
Please, anyone could suggest any idea to how I implement it?
Thank you.

**Comment by srawlins** [comment]
We generally cannot answer framework-specific questions here. No Flutter experts :/. StackOverflow is your best bet.

If this is not framework-specific, we need more information; this is not a complete example. What is `userMocked`, what does `User` look like? What about `mockManager`? What is a SynchronousFuture, that looks weird? And `mockPresenter` and `mockView`. What is the expected behavior? What is the actual behavior?
