### ISSUE TITLE
Annotation and code generator

### ISSUE THREAD

**Issue by adsonpleal** [dart-lang/mockito#222]
What do you guys think about code generation?

I've created a new package that generates the mock classes from annotations.

Package: https://pub.dev/packages/mockito_code_generator

The main idea is something like this:

```dart
part 'my_test.g.dart';

@BuildMock()
Cat _cat;

void main() {
  setUp(() {
    // Init mocks.
    _initMocks();
  });

  test("Let's verify some behavior!", () {
    _cat.sound();
    verify(_cat.sound());
  });
```

The generated code looks like:

```dart
part of 'my_test.dart';

class CatMock extends Mock implements Cat {}

void _initMocks() {
  _cat = CatMock();
}
```

**Comment by srawlins** [comment]
We are planning a code generation mode for Mockito to be written for Dart's upcoming Non-nullable-by-default (NNBD) type system. This type system will not be happy with `any` returning `null`, so mockito will need to change. After looking at different options, we're introducing a code generation mode to help with transitioning to NNBD.

**Comment by natebosch** [comment]
I do like the idea of driving the _definition_ of an `extends Mock` class with codegen, it dissuades the antipattern of trying to put `@override` methods in a mock which is not a sensible thing to do. I would hope that making it even easier to make mocks wouldn't push us further into overuse of mocks...

**Comment by leecommamichael** [comment]
> I do like the idea of driving the _definition_ of an `extends Mock` class with codegen, it dissuades the antipattern of trying to put `@override` methods in a mock which is not a sensible thing to do. I would hope that making it even easier to make mocks wouldn't push us further into overuse of mocks...

Could you elaborate on overrides in mocks as an anti-pattern?

**Comment by natebosch** [comment]
> Could you elaborate on overrides in mocks as an anti-pattern?

We discuss it just a bit in https://github.com/dart-lang/mockito#best-practices

The overall testing practice has a lot of discussion generally around the internet. Here is at least one article discussing some of the downsides to overusing mocks. https://testing.googleblog.com/2013/05/testing-on-toilet-dont-overuse-mocks.html

At a high level some of the risks are:
- If you mock doesn't match the real class your test is invalid.
- Mocks can add a lot of noise to the test and drown out the intent.
- Tests can become brittle if you overspec a mock against what the test _does_ instead of what it is _intended to do_.

Generally a mock is most useful when:
- The test needs to `verify` that a method was called because of it's _side effects_. Like a network request or storing something in a database.
- The behavior would otherwise be too slow or complex to integrate into a test.

**Comment by srawlins** [comment]
We've shipped our code-generation solution.
