### ISSUE TITLE
Unexpected behavior when calling verify multiple times

### ISSUE THREAD

**Issue by mentoc3000** [dart-lang/mockito#245]
After `verify` is called on a mocked object method, the record of that call is erased from the mocked object, leading to unexpected behavior.

```dart
class Foo {
  bar(int x) => null;
}

class MockFoo extends Mock implements Foo {}

void main {
  test('multiply verified', () {
    final foo = MockFoo();
    foo.bar(1);
    verify(foo.bar(1)).called(1);
    verify(foo.bar(1)).called(1);
  }

  test('two verified conditions', () {
    final foo = MockFoo();
    foo.bar(1);
    foo.bar(2);
    verify(foo.bar(1)).called(1);
    verify(foo.bar(any)).called(2);
  }
}
```

**Expected Behavior**

All tests pass.

**Actual Behavior**

The first test fails at `verify(foo.bar(1)).called(1)` with message

```
No matching calls. All calls: [VERIFIED] MockFoo.bar(1)
(If you called `verify(...).called(0);`, please instead use `verifyNever(...);`.)
```

The second test fails at `verify(foo.bar(any)).called(2)` with message

```
Expected: <2>
  Actual: <1>
Unexpected number of calls
```

**System Information**
Dart VM version: 2.8.0-dev.18.0
Mockito v4.1.1

**Comment by srawlins** [comment]
This is expected behavior. However it does not appear to be documented.

**Comment by mentoc3000** [comment]
Why is that the desired behavior? It seems nonintuitive in the examples I gave.

**Comment by srawlins** [comment]
I think the idea is that a developer probably only wants to verify a behavior once. Your first example:

```dart
verify(foo.bar(1)).called(1);
verify(foo.bar(1)).called(1);
```

is a not typical (I'm sure you were just simplifying for a minimal repro); why verify twice in a row? What is more typical is to take some action, verify, take _more_ action, verify again. In this case, you don't want a verification to have passed because of earlier activity.

Also it would make the [captured arguments](https://github.com/dart-lang/mockito#capturing-arguments-for-further-assertions) in a `verify` more complicated. (Confidence in which call is being captured; an earlier one? a later? One which was already verified?)

**Comment by mentoc3000** [comment]
The use case that I have is more aligned to the second example. I want to verify that a call was made to a method with certain parameters _and_ that there were no other calls to that method. Reading that syntax is odd.

```
verify(foo.bar(1)).called(1);
verify(foo.bar(any)).called(0);
```

**Comment by srawlins** [comment]
For this, I would use [`verifyNoMoreInteractions`](https://github.com/dart-lang/mockito#finding-redundant-invocations). If there are unrelated interactions with other methods that prevent `verifyNoMoreInteractions` from being useful, I'd just put a comment above the second verification.

**Comment by mentoc3000** [comment]
Thank you!
