### ISSUE TITLE
then() evaluates to null in verify()

### ISSUE THREAD

**Issue by FaFre** [dart-lang/mockito#257]
I stumbled upon this unexpected behavior, where I could not access the `thenReturn()` result within `verify()`.

```dart
    when(HiveManager()
            .interface
            .box(HiveManager().repository.getBoxName<Issue>()))
        .thenReturn(MockIssueBox());

    expect(
        HiveManager()
            .interface
            .box(HiveManager().repository.getBoxName<Issue>()),
        isNotNull);

    verify(HiveManager()
        .interface
        .box(HiveManager()
            .repository
            .getBoxName<Issue>()) //.box() is suddenly null
        .put(issue.entityKey, issue));
```

However I can workaround that by simply capture `box` before `verify()` first:

```dart
    when(HiveManager()
            .interface
            .box(HiveManager().repository.getBoxName<Issue>()))
        .thenReturn(MockIssueBox());

    final box = HiveManager()
        .interface
        .box(HiveManager().repository.getBoxName<Issue>());

    verify(box.put(issue.entityKey, issue));
```

This behavior is very unnatural and hard to track down (if it's not considered a bug).

**Comment by natebosch** [comment]
The structure of a call to `when` or `verify` should be `when(mockInstance.mockedMethod())`. A few things stand out about your code.

`when(HiveManager().interface.box` - `HiveManager().interface` _must_ be returning a static instance of a mock here.

It's also true that the behavior _inside_ those parenthesis past `when` or `verify` will not get mocked behavior.

The typical way to write this would be closer to:

```dart
var hiveManagerInterfaceMock; // This would need to be set to the same instance of the mock as HiveManager().interface returns
var mockIssueBox = MockIssueBox();
when(hiveManagerInterfaceMock.box(HiveManager().repository.getBoxName<Issue>()))
    .thenReturn(mockIssueBox);
// something that calls `.box` on the _exact_ instance hiveManagerInterfaceMock
verify(mockIssueBox.put(issue.entityKey, issue));
```

Overall the design seems fairly non-idiomatic here.

When it comes to mockito the important thing to remember is that you are mocking behavior on _instances_ of the mock. Those instances are generally referenced by variable in the test, not reference by pulling them out of other mocks.

Especially not that `.thenReturn(SomeMockClass())` is likely not useful, because you don't have any other reference to that _instance_ of `SomeMockClass` so you can't mock methods on it or verify calls.

For future questions of this nature Stack Overflow is likely a better support avenue.
