### ISSUE TITLE
Enhancement: Mocking extension members

### ISSUE THREAD

**Issue by ResoDev** [dart-lang/mockito#263]
I am fully aware of the current limitations of this otherwise amazing library. For example, we cannot mock static or top-level methods. Since extensions are really just static members in disguise, Mockito doesn't support them as well.

Extension methods can simplify code a lot and I'd like to use them. However, the inability to use them with mocks forces me to create ugly wrapper classes.

The following code outputs `ERROR: Bad state: Mock method was not called within when(). Was a real method called?` and also runs the actual code inside the `userRef()` extension method.
```dart
when(mockFirebaseStorage.userRef())
    .thenAnswer((_) async => mockRootStorageReference);
```
Mockito shouldn't prevent us from using newer language features.

**Comment by srawlins** [comment]
> Mockito shouldn't prevent us from using newer language features.

How does mockito prevent one from using newer language features? Can you give an example? (In your code snippet, what are `mockFirebaseStorage` and `userRef()`?)

**Comment by ResoDev** [comment]
I mean that we can't mock extension methods.

`mockFirebaseStorage` is simply an instance of
```dart
class MockFirebaseStorage extends Mock implements FirebaseStorage {}
```
and `userRef()` is an extension method
```dart
extension FirebaseStorageX on FirebaseStorage {
  Future<StorageReference> userRef() async {
    // ...
  }
}
```

**Comment by ResoDev** [comment]
I mean that we can't mock extension methods.

`mockFirebaseStorage` is simply an instance of
```dart
class MockFirebaseStorage extends Mock implements FirebaseStorage {}
```
and `userRef()` is an extension method
```dart
extension FirebaseStorageX on FirebaseStorage {
  Future<StorageReference> userRef() async {
    // ...
  }
}
```

**Comment by natebosch** [comment]
Mockito does not prevent you from using extension methods, you can mock out the behavior used by the extension instead of the entire extension. It also does not allow you to _mock_ extension methods, because the language fundamentally does not support that.

Just as with any other static methods which can't be mocked - it is your choice to use them or avoid them. Personally I don't avoid these language features and if I find myself missing the ability to mock out some bit of static functionality I consider it a design smell (overly tight coupling) or testing smell (over reliance on mocking).

This issue is not actionable in this package.

**Comment by LHDi** [comment]
Is there a known method to do so (Mock the behavior of extension ) because I couldn't get it to work.

**Comment by srawlins** [comment]
There is no method to mock extension methods. This is [already documented](https://github.com/dart-lang/mockito/blob/master/FAQ.md#how-do-i-mock-an-extension-method).

**Comment by LHDi** [comment]
I meant the behavior used by the extension as @natebosch mentioned: 

> ... you can mock out the behavior used by the extension instead of the entire extension.

and can I apply it to an external package such as permission_handler?
They used extension methods to implement the package, So is it **unMockable**

Thank you.

**Comment by natebosch** [comment]
There is no magic here - mocking the behavior that is _used_ is what you already do with mocks. You are accustomed to mocking the behavior that is used by _your_ code under test - that is the purpose of the mock. When I say to mock the behavior _used by the extension_, I mean to treat the extension that your code under test calls like any other code in the implementation.

To make this explicit consider this trivial example:

```dart
abstract class Foo {
  int get a;
  int get b;
}

extension AandB on Foo {
  int get aAndB => a + b;
}
```

You know that your code under test calls `someFoo.aAndB`, and so you wish that you could do `when(mockFoo.aAndB).thenReturn(10);`, but since `aAndB` is an extension member you can't do that. Instead, you need to do:

```dart
when(mockFoo.a).thenReturn(4);
when(mockFoo.b).thenReturn(6);
```

And when your code under test reads `aAndB` it will get the intended value `10`. What this is doing is forcing the test to match the _actual_ requirements/behavior of the code under test - which is that the 2 fields `a` and `b` sum to `10`.

**Comment by LHDi** [comment]
Thank you @natebosch I found your answer very helpful.
I think it's now clear that this is not a **Mockito** issue.

**Comment by kuhnroyal** [comment]
Just wanted to add a possible way to circumvent this limitation in tests. You can create an interface/abstract class in a test that has the same method signature as the extension and mock this instead.

```dart
extension Foo on String {
 bool get isBar => false;
}

abstract class _FooExtension {
  bool get isBar;
}

class MockObject extends Mock implements String, _FooExtension {}

when(MockObject().isBar).thenReturn(true);
```

This has worked well for me and should maybe be document as a workaround.
