### ISSUE TITLE
Latest master broke the build

### ISSUE THREAD

**Issue by fryette** [dart-lang/mockito#291]
Hi, unfortunately, I have to switch on the master to make possible support for the latest analyzer.
Before all commits(Commits on Oct 20, 2020) everything was fine, today I see the author pushed some changes and now my build_runner failed with the next errors:

Asset [lib/my_file.dart] is not a Dart library. It may be a part file or a file without Dart source code.
[SEVERE] mockito:mockBuilder on lib/my_file.dart:

**Comment by srawlins** [comment]
Thanks for the issue report. Can you point me to your build.yaml, and your `build_runner` command?

**Comment by natebosch** [comment]
This is likely because we are auto applying the builder now.

@fryette - you can either add a config in your `build.yaml` for now which disables the mockito builder, or you can update your dependency to point to the commit before the one which broke you. In general the master branch isn't guaranteed to be stable.

@srawlins - I wonder if an empty file causes an issue with `Resolver.libraryFor` (or `buildStep.inputLibrary`)...

**Comment by srawlins** [comment]
Eek. There is an issue with part files. If I make a valid part file in a package's` lib/` folder, and make it a part of a valid library file in `lib/`, and run `pub global run build_runner build`, I see the crash. I'll write a fix today and get it to master ASAP.

**Comment by srawlins** [comment]
Fixed by https://github.com/dart-lang/mockito/commit/7fafa309482ac68f5fdac0bc59153222b5caa2fa
