### ISSUE TITLE
Suggestions for non-nullable api

### ISSUE THREAD

**Issue by KalilDev** [dart-lang/mockito#305]
While migrating an package, i noticed that the Object props (hashCode, operator==, runtimeType and toString()) were throwing when the dart: libraries used any, because i did not stub them, and stubbing them would be really cumbersome, so i temporarily modified the generated code and after that a lot of tests passed successfully.

For an faster migration on `--no-sound-null-safety` i enabled `returnNullOnMissingStub`, then i continued with the migration and after i finished i moved to sound-null-safety, and noticed that a lot of `Future<void>` returns needed to be stubbed, and this resulted in more verbose tests.

So, my suggestions for the MockSpec and related codegen are:
- Add either an `stubObjectMethods` bool parameter or an `doNotStub` List\<Symbol\> parameter with an list of methods/accessors to not have mockito code generated. Then store the List<Symbols> that should throw an error in case noSuchMethod is called with them, informing the user that such method/accessor should not be used on `when` statements or that they should have an concrete implementation in case they were used on a real call.
- Add either an `returnValidNullableFutureOnMissingStub` bool parameter or an `returnFakeOnMissingStub` List\<Symbol\> which will in the first case return an Future.value() on Future\<dynamic\>, Future\<T?\> or Future\<void\>, or in the second case, a more general approach, it will return the Fake value that was used as the second parameter on noSuchMethod, which is always of the correct type, but not usable.

Also, now that `any`, `anyNamed`, `captureAny`, `captureAnyNamed`, `argThat` and `captureThat` can not be used with non-nullable parameters, maybe an option for having the same functionality would be to add an non-fluent api that allows the user to manually create the argument matchers, for example, `when(mockObject, #get).matchParams(none).thenReturn(1)` would return 1 in case there was `get` call with 0 positional parameters, and `when(mockObject, #set).matchParams([anyValue, equals(1)]).thenThrow('invalid')` which would throw 'invalid' when trying to call #set and the second param is 1.

**Comment by srawlins** [comment]
Thanks for the report, @KalilDev , can you say what version of mockito you are using?

**Comment by KalilDev** [comment]
I'm using `5.0.0-nullsafety.0` from the https://github.com/dart-lang/mockito/commit/c387e344084c81865b29ddef8e76f85874023ff1 revision. Thanks for the swift response!

**Comment by srawlins** [comment]
@KalilDev at first I did not understand your first request, which is why I asked for your version; it's a total red herring 😆 .

It is _really_ good to get this real-world feedback on features like throw-on-missing-stub. I get the idea that you should provide stubs for methods that code you care about in tests calls, but if code somewhere calls `toString()`, then you probably don't care a lot about that.

I'm curious though, I am surprised that mocks in tests have these methods called on them a lot, causing you to have to write a bunch of stubs.

Can you give examples about the `Future<void>` problem? I think I have a sense of what you're getting at, but I'm not 100% sure.

**Comment by srawlins** [comment]
> maybe an option for having the same functionality would be to add an non-fluent api that allows the user to manually create the argument matchers, for example, when(mockObject, #get).matchParams(none).thenReturn(1)

Yeah this came up when designing the code-gen idea. "What about a whole new API?" I think it might be possible to design a sibling API which is completely separate from the current `when(obj.method(any)).thenReturn(x)` API, which doesn't have the same ugly non-nullable issues. For the time being, I think we want to focus on the one API, migrating code inside Google to the new API, in particular, and see if we want to support two separate user-facing APIs.

**Comment by KalilDev** [comment]
> @KalilDev at first I did not understand your first request, which is why I asked for your version; it's a total red herring laughing .

Yeahh, makes sense

> I'm curious though, I am surprised that mocks in tests have these methods called on them a lot, causing you to have to write a bunch of stubs.

The problem with the Object properties was mostly because of hashCode and the equality operator. In hive some mock objects were being used as keys in maps, resulting in hashCode calls, and they were also being compared, which used the operator.

> Can you give examples about the `Future<void>` problem? I think I have a sense of what you're getting at, but I'm not 100% sure.
Yes, for example i wanted to test `BoxImpl.putAll`, which internally calls `MockBackend.writeFrames` and `MockBackend.compact`, both of which return `Future<void>` and are just an implementation detail, but had to be stubbed now, otherwise they would throw, whereas before they didn't have to be stubbed.

Here are some examples of stubs added because of `Future<void>`:
- https://github.com/hivedb/hive/pull/521/files#diff-468c3c639d3eb0d01489cd82fe3f39f389a68c27ebd9dbaff757d89dd23b3873R93
- https://github.com/hivedb/hive/pull/521/files#diff-468c3c639d3eb0d01489cd82fe3f39f389a68c27ebd9dbaff757d89dd23b3873R122
- https://github.com/hivedb/hive/pull/521/files#diff-468c3c639d3eb0d01489cd82fe3f39f389a68c27ebd9dbaff757d89dd23b3873R144
- https://github.com/hivedb/hive/pull/521/files#diff-468c3c639d3eb0d01489cd82fe3f39f389a68c27ebd9dbaff757d89dd23b3873R161
- https://github.com/hivedb/hive/pull/521/files#diff-468c3c639d3eb0d01489cd82fe3f39f389a68c27ebd9dbaff757d89dd23b3873R207
- https://github.com/hivedb/hive/pull/521/files#diff-468c3c639d3eb0d01489cd82fe3f39f389a68c27ebd9dbaff757d89dd23b3873R285
- https://github.com/hivedb/hive/pull/521/files#diff-468c3c639d3eb0d01489cd82fe3f39f389a68c27ebd9dbaff757d89dd23b3873R328
- https://github.com/hivedb/hive/pull/521/files#diff-468c3c639d3eb0d01489cd82fe3f39f389a68c27ebd9dbaff757d89dd23b3873R380
- https://github.com/hivedb/hive/pull/521/files#diff-468c3c639d3eb0d01489cd82fe3f39f389a68c27ebd9dbaff757d89dd23b3873R416
- https://github.com/hivedb/hive/pull/521/files#diff-73f6ab85395367996eda774920bd9fbf9d070878b1c262fe97e1201e33a29af4R101
- https://github.com/hivedb/hive/pull/521/files#diff-73f6ab85395367996eda774920bd9fbf9d070878b1c262fe97e1201e33a29af4R183
- https://github.com/hivedb/hive/pull/521/files#diff-67da8c814f730d72936b54eed35fa01c017bc2ade0c35d6cd3d3a3106087004cR148
- https://github.com/hivedb/hive/pull/521/files#diff-cfb9c93cf1f1ab964d22fa5efe56eccd310c0a11650e346627a794b23e25f2c3R109
- https://github.com/hivedb/hive/pull/521/files#diff-cfb9c93cf1f1ab964d22fa5efe56eccd310c0a11650e346627a794b23e25f2c3R128

These are the cases that i could not test with the current mockito null safe api because of the `Future<void>` problem. Although, i just noticed that `DeepCollectionEquality` is used to compare the maps and lists, so i will be able to test them, my bad.
- https://github.com/hivedb/hive/pull/521/files#diff-5af9a8b3c35ab16d26bd3221b6834ca3431fb773cf490deea4c63e1cf4cb624bR29
- https://github.com/hivedb/hive/pull/521/files#diff-468c3c639d3eb0d01489cd82fe3f39f389a68c27ebd9dbaff757d89dd23b3873R251
- https://github.com/hivedb/hive/pull/521/files#diff-468c3c639d3eb0d01489cd82fe3f39f389a68c27ebd9dbaff757d89dd23b3873R224

Elaborating on my suggestion of `returnFakeOnMissingStub`, they would be good for testing APIs which perform side effects but whose return value is not used, for example, `File.delete`, which returns an `Future<FileSystemEntity>`, `RandomAccessFile.lock`, which returns an `Future<RandomAccessFile>`. Just returning an unusable `Fake` would avoid the need for stubbing them.

Here are some examples of stubs which had to be added when the fake value would suffice:

Reason: The returned future is returned as `Future<void>`, so the return value is ignored

Here, the value being discarded: https://github.com/hivedb/hive/blob/master/hive/lib/src/io/buffered_file_writer.dart#L28
- https://github.com/hivedb/hive/pull/521/files#diff-9054171a84b73bcc15b8fc0764f975eacd61bb55a59576a62a5063471bf929caR18
- https://github.com/hivedb/hive/pull/521/files#diff-9054171a84b73bcc15b8fc0764f975eacd61bb55a59576a62a5063471bf929caR26
- https://github.com/hivedb/hive/pull/521/files#diff-9054171a84b73bcc15b8fc0764f975eacd61bb55a59576a62a5063471bf929caR33

Reason: The returned futures are just awaited, but never stored or used.

Here: https://github.com/hivedb/hive/blob/master/hive/lib/src/backend/vm/storage_backend_vm.dart#L77 , https://github.com/hivedb/hive/blob/master/hive/lib/src/backend/vm/storage_backend_vm.dart#L90 , https://github.com/hivedb/hive/blob/master/hive/lib/src/backend/vm/storage_backend_vm.dart#L101 , https://github.com/hivedb/hive/blob/master/hive/lib/src/backend/vm/storage_backend_vm.dart#L127 , https://github.com/hivedb/hive/blob/master/hive/lib/src/backend/vm/storage_backend_vm.dart#L129
- https://github.com/hivedb/hive/pull/521/files#diff-da1f9e3c71f600e09e9b80d5542282d0de16e13525be7cb5324cbc16b9a41536R134
- https://github.com/hivedb/hive/pull/521/files#diff-da1f9e3c71f600e09e9b80d5542282d0de16e13525be7cb5324cbc16b9a41536R161
- https://github.com/hivedb/hive/pull/521/files#diff-da1f9e3c71f600e09e9b80d5542282d0de16e13525be7cb5324cbc16b9a41536R162
- https://github.com/hivedb/hive/pull/521/files#diff-da1f9e3c71f600e09e9b80d5542282d0de16e13525be7cb5324cbc16b9a41536R181
- https://github.com/hivedb/hive/pull/521/files#diff-da1f9e3c71f600e09e9b80d5542282d0de16e13525be7cb5324cbc16b9a41536R239
- https://github.com/hivedb/hive/pull/521/files#diff-da1f9e3c71f600e09e9b80d5542282d0de16e13525be7cb5324cbc16b9a41536R240
- https://github.com/hivedb/hive/pull/521/files#diff-da1f9e3c71f600e09e9b80d5542282d0de16e13525be7cb5324cbc16b9a41536R257
- https://github.com/hivedb/hive/pull/521/files#diff-da1f9e3c71f600e09e9b80d5542282d0de16e13525be7cb5324cbc16b9a41536R258
- https://github.com/hivedb/hive/pull/521/files#diff-da1f9e3c71f600e09e9b80d5542282d0de16e13525be7cb5324cbc16b9a41536R360
- https://github.com/hivedb/hive/pull/521/files#diff-da1f9e3c71f600e09e9b80d5542282d0de16e13525be7cb5324cbc16b9a41536R361

**Comment by KalilDev** [comment]
> > maybe an option for having the same functionality would be to add an non-fluent api that allows the user to manually create the argument matchers, for example, when(mockObject, #get).matchParams(none).thenReturn(1)
> 
> Yeah this came up when designing the code-gen idea. "What about a whole new API?" I think it might be possible to design a sibling API which is completely separate from the current `when(obj.method(any)).thenReturn(x)` API, which doesn't have the same ugly non-nullable issues. For the time being, I think we want to focus on the one API, migrating code inside Google to the new API, in particular, and see if we want to support two separate user-facing APIs.

Yes, completely understandable

**Comment by denniskaselow** [comment]
Something else that may need a different default behavior are `setter` and `void` functions.

Calling a void function on a mocked class just throws this:
```
dart:core                             Object.noSuchMethod
package:mockito/src/mock.dart 149:22  Mock._noSuchMethod
package:mockito/src/mock.dart 143:45  Mock.noSuchMethod
package:foobar/foobar.dart 4:8        MockFoo.doSomething
test\foobar_test.dart 13:9            main.<fn>

NoSuchMethodError: Class 'Object' has no instance method 'doSomething'.
Receiver: Instance of 'Object'
Tried calling: doSomething()
```

And calling a setter on a mocked class throws this:
```
dart:core                             Object.noSuchMethod
package:mockito/src/mock.dart 149:22  Mock._noSuchMethod
package:mockito/src/mock.dart 143:45  Mock.noSuchMethod
test\foobar_test.mocks.dart 16:13     MockFoo.content=
test\foobar_test.dart 18:9            main.<fn>

NoSuchMethodError: Object has no content setter
```

with this being the mocked class:
```dart
class Foo {
  String content = 'content';
  void doSomething() {}
}
```
and this the test:
```dart
@GenerateMocks([Foo])
void main() {
  test('call void function', () {
    final foo = MockFoo();

    foo.doSomething();
  });
  test('call a setter', () {
    final foo = MockFoo();

    // doesn't make a difference whether it's a field or an actual setter
    foo.content = '';
  });
}
```

It works when using `returnNullOnMissingStub: true` but those are common enough operations that they should work with the default, otherwise there aren't a lot of cases where you can use the default behavior.

**Comment by KalilDev** [comment]
Dennis, this happens because you did not stub the setter and function in an null-safe library. The mockito codegen automatically opts in throwing on missing stub, and in `noSuchMethod`, mockito checks if the method is stubbed, and if it is not it calls the default response, which is calling `noSuchMethod` on an `const Object()`, which in turn throws `NoSuchMethodError`. Using `returnNullOnMissingStub` only works with unsound null safety, and trying to run the tests with sound null safety will result in `TypeError`s, because the returned `null` is not an valid value of an non nullable type `T`

**Comment by KalilDev** [comment]
I thought a long while about this, and with that, i think that:
- Stubbing Object properties should be opt in only, with an bool flag in MockSpec
- Trying to call an unstubbed function/accessor whose fake return value is an primitive (bool, int, String) should throw, as the fake return value is valid and usable and may result in unexpected behavior when testing.
- Trying to call an unstubbed function/accessor should return the Fake value generated by mockito codegen and is expected to be discarded, and when trying to use any method/accessor, an error should be thrown instructing the user to stub said method/accessor. Maybe including the method/accessor name and `MockTypeName` on the `Fake` constructor is a good idea, so he can know exactly where this value came from, instead of trying to guess which method/accessor he forgot to stub.

I think i will implement an prototype of this api and check how it feels like.

**Comment by denniskaselow** [comment]
Maybe I'm missing something, but how would I go about stubbing a void function?

```dart
when(foo.doSomething()).thenAnswer((_) {});
```

works, but is that really what I'm expected to with nullsafety? I'd expect void functions and setters to be pretty much noops unless you do something with `thenAnswer` or `verify` and I wouldn't expect them to return anything (neither `null` nor a `Fake`). And concerning setters I must be missing something really basic, because I don't even know how I would go about doing that. `when(foo.content)` only works for the getter. Probably because I never had to, but I can't see anything in the README nor the NULL_SAFETY_README on how to do that.

Concerning stubbing `Object` properties (if you are reffering to `hashcode`, `toString()`, `==` and `runtimeType`) I think the old behavior would be the correct one, that is, using the function `hashcode`, `toString()` and `==` from the `Mock` class and `runtimeType` from the `Object` class instead of the code generator overriding them in the generated code.

**Comment by KalilDev** [comment]
> I think i will implement an prototype of this api and check how it feels like.

Here, i made the prototype and created a test case to demonstrate the usability: https://github.com/KalilDev/mockito/commit/4b8423de1259c139c9eb9c13d03a695bb0882479

**Comment by razamatan** [comment]
re: "primitive" return values: instead of throwing and acting like a Fake for a Mock, can the Mock just return a standard/sane default (0, 0.0, false, '').  if i had to make a strong argument for just one of these, i would strongly want bool to just always return false.  bools are important b/c dart compliation/transpilation barfs when evaluating boolean expressions in branches where the mock returns null (not of type bool in a boolean expression).

1.  this is consistent with what mockito's mock spec is (returning a constant value: null for everything but the "primitives") vs mixing fake behavior of throwing on unsepcified test behavior
2. it's reasonable to assume that if the return value being a valid value has impact, then the dev should be aware of this and properly stub it over

**Comment by razamatan** [comment]
https://github.com/dart-lang/mockito/commit/cee9efd508b587113868d38a296f37702e3c45a3 doesn't address primitive bool return values returning nulls in mocks...?

**Comment by srawlins** [comment]
@razamatan That is correct. The motivation that I used for methods that return `void` (like setters) or `Future<void>` is that there is sort of nothing to stub. If you have a class:

```
abstract class C {
  void set a(int value);

   bool isSomething(int x, int y);
}
```

then a user might want to allow code-under-test to call `c.a = 7`, given `MockC c`, without the system throwing saying "you forgot to stub `a=`!!" The remedy for that situation is quite strange, because stubbing is largely (but not entirely) about return values, as @denniskaselow pointed out. You would tell Mockito to stub `a=` with a function that ... does nothing.

All that said, I think it _does_ make sense to require a stub for `isSomething`. If code-under-test calls `c.isSomething(1, 2)`, but you have not declared any stubs that match that call, then who is Mockito to pick a return value (either true or false), which your code-under-test will then use in possibly surprising ways.

An important consequence of that proposed behavior is that it would lead to very-hard-to-diagnose test bugs. Devs unfamiliar with the default return values (like `false`, `0`, `''`) would really be scratching their heads at the weird return values coming out of their mocks.

**Comment by srawlins** [comment]
@KalilDev I wrote "Fixes #305" in some commit message, but please re-open, or file a new bug, if you don't think I addressed the concerns you raised. I think `void` and `Future<void>` were the important ones to hit though...

**Comment by razamatan** [comment]
but if they want to get breaking exceptions for unimplemented things, a fake is warranted no?  why isn't the current stub behavior of always returning null not surprising already given your rationale?  to me, deciding to return a reasonable, consistent default for the classic "primitives" seems reasonable and consistent and won't break things beyond what silent null return values currently do.
________________________________

**Comment by srawlins** [comment]
> why isn't the current stub behavior of always returning null not surprising already given your rationale?

We believe it _was_ surprising, which is why `throwOnMissingStub` was introduced.

> and won't break things beyond what silent null return values currently do.

Right, but we think silent null is already bad, and that throwing on missing stubs is better than returning null, or sane values.

I think it is perhaps reasonable to support the old "just return something" way in 'null safe' type system for simple types, as you are suggesting, but not with the default generated mocks. I think we can add another flag to the custom mocks. Right now there is `returnNullOnMissingStub`. Perhaps we can change this or add "returnSimpleDefaultOnMissingStub`.

**Comment by razamatan** [comment]
ok.  thanks for the clarifications.  having a "simple default" option would be nice, too. :)

generally, what would be the purpose of Mock over Fake in the direction things are headed?
