### ISSUE TITLE
Support 'Object operator ==(dynamic other))'

### ISSUE THREAD

**Issue by quanbui1998** [dart-lang/mockito#479]
I use a library but it is write a class which override operator ==(dynamic other) so dart display error:

`'Object.==' ('bool Function(Object)') isn't a valid concrete implementation of 'Record.==' ('bool Function(dynamic)').`

```
@override
  bool operator ==(dynamic other) {
     ...
  }
```

Can you fix `mockito` for support  ` operator ==(dynamic other)`? Thanks!

**Comment by eernstg** [comment]
With null safety (that is, since language version 2.12), `operator ==` accepts an argument of type `Object`. It is possible to create an override whose signature is `bool operator ==(dynamic)`, but that is misleading and unnecessary because the semantics of `e1 == e2` ensures that the `operator ==` will _never_ be invoked with null as the actual argument.

I don't know the details of your code, but the problem probably arises when a class has an interface where `operator ==` has a parameter of type `dynamic`, and it inherits an implementation whose parameter type is `Object`. That is not a correct override (because that implementation should be able to accept `null` as its argument, but it cannot do that).

So the fix would be to get that declaration of `operator ==(dynamic arg)` fixed.

**Comment by natebosch** [comment]
I'll close this since there is a workaround and it isn't a pattern we'd like to encourage.
