### ISSUE TITLE
Create shorthand annotations like @Mock in Java

### ISSUE THREAD

**Issue by xster** [dart-lang/mockito#51]
http://static.javadoc.io/org.mockito/mockito-core/2.7.0/org/mockito/Mock.html

Reduce the boilerplate of having to:
```dart
MockSomething extends Mock implements Something {}

void main() {
  MockSomething mockSomething;

  setUp(() {
    mockSomething = new MockSomething();
  }

  test('test using something', () {
    use mockSomething
  });
}
```
to
```dart
void main() {
  @Mock Something mockSomething;

  test('test using something', () {
    use mockSomething
  });
}
```

**Comment by matanlurey** [comment]
This is unlikely to happen as it isn't a supported language feature.

There has been _some_ discussion about different types of macro syntaxes for a future version of Dart, but nothing concrete I can link back to and be affirmative will show up. If we do add something we'll definitely try to keep this use case in mind, though.

(Closing in order to affirm this can't happen from the Mockito perspective)
