### ISSUE TITLE
is mokito support test of http at all?

### ISSUE THREAD

**Issue by alirezat66** [dart-lang/mockito#520]
I worked more than 8 hours to solve the problem but it didn't solve. so I ask you to check that part it seems the problem is taken with mokito.
` final url = Uri.parse('http://numbersapi.com/$tNumber');

      //arrange
      when(mockHttpClient
              .get(url, headers: {'Content-Type': 'application/json'}))
          .thenAnswer((_) async => Response(fixture('trivia.json'), 200));
`
that is my code but I get the 'type nul is not a subtype of type Future<Response>"

**Comment by srawlins** [comment]
A question like this is best asked on a forum like StackOverflow, where many people can look at and help with the problem. The Dart team is small and may not be able to review this question.

In a case where the actual behavior does not match the expected behavior, make sure to include a complete example, the expected result, and the actual result. Your message above does not include a full example, and I suspect the error you posted is not exactly what you see, as "nul" is misspelled.
