### ISSUE TITLE
Add support for manually creating defaults for non-null return values

### ISSUE THREAD

**Issue by natebosch** [dart-lang/mockito#523]
If we can't create a fake subclass to use when returning non-null from an unstubbed invocation the workaround today is to create a fallback for each method that returns that type. A way to define default values keyed by the value type may reduce noise in some cases, and may be a more obvious conceptual match for the problem the author is trying to solve.

**Comment by zhanglix** [comment]
I think it can also simply mocking code too. #589 #592

**Comment by yanok** [comment]
AFAIU this request, this is implemented now. @natebosch can we close this?

**Comment by natebosch** [comment]
I don't think this is implemented. We have `@GenerateNiceMocks` which works around this issue currently by returning fakes always. It would still be worthwhile to have a way to specify a `const Map<Type, Object> defaultReturnValues` to get some other default returns than fakes. This would also give us a way to work around some of our problems with `final` and `base` super classes for return values.

**Comment by srawlins** [comment]
I think @yanok was referring to https://github.com/dart-lang/mockito/commit/3fadd2d8015c57cc851dbb121efa1bf8d658d8db.

**Comment by natebosch** [comment]
Ah, I missed it when that feature went in. That does look like it can solve the runtime problem, but doesn't help much with the codegen problem.

**Comment by yanok** [comment]
Hm... I'm not sure I follow. What's the codegen problem? Now codegen ends up looking up for run-time provided values in two (potentially three) cases:
 1. Type is unknown at compile-time (type variable),
 2. Unfakable (`final`/`base`/`sealed`) class.
 3. (not done yet) private types, since sometimes users can provide dummies for them (if there is a public value that has the required _static_ type, users can call `provideDummy` without type argument and type inference will do the trick).

We could also pass a map `Type` -> `defaultValue` to the codegen, but I don't really see any benefits:

 1. It seems, everything that could be solved by passing `defaultReturnValues` map to the codegen, could also be solved with `provideDummy` function.
 2. On the contrary, using such a map in codegen in useless in 2 out of 3 potential use cases:
     * Unknown types are unknown, nothing to look for.
     * For private types users won't be able to add an entry to the map.
 3. It may look like doing the lookups at compile time in codegen is safer than at run time, so "if it compiles, it works". But for this to be true, we would have to revert the run-time lookups completely, and they are essential for the "type variable" case.
 
Or am I missing something?

**Comment by natebosch** [comment]
> Or am I missing something?

No, static checking is the main benefit, but if we don't expect to get to full static checking there probably isn't enough value in handling it during codegen.
