### ISSUE TITLE
Issue with anyNamed and any

### ISSUE THREAD

**Issue by stevenosse** [dart-lang/mockito#630]
I'm facing an issue when i use anyNamed and any methods.

The implementation of any and anyNamed matchers uses Null as the return type which breaks the compilation with the error:
`The argument type 'Null' can't be assigned to the parameter "Type"`.

My take is that it should use a generic type :
Instead of the signature : `Null anyNamed(String named)` we would have `T anyNamed<T>(String name)`

**Comment by srawlins** [comment]
All parameters where `any` or `anyNamed` is given should be nullable, so that those are valid. Can you show how you are generating mocks with `@GenerateNiceMocks` (as in the [README](https://github.com/dart-lang/mockito)) which yields a mock class with a parameter that cannot accept a null value? Also please show the declaration of the variable which is a mock (like `MockFoo foo;`) to make sure that the static type also has nullable parameters. Thanks!

**Comment by yanok** [comment]
@stevenosse ping, could you please clarify, what is the issue exactly?

Return type of `any` and `anyNamed` is intentionally `Null`, since they do return `null`, so that would have to be changed, if we would like to change the return type. Technically we could do that now for `anyNamed` and use recently added dummy value lookup to get the correct value for the requested type. But...

1. This won't work for `any`: it's a getter and getters can't be generic (feel free to vote on https://github.com/dart-lang/language/issues/1622 to add them, but it's not going to be tomorrow anyway), so I don't think there is a lot of sense to change it for `anyNamed` if we can't do the same for `any`.
2. This will require users to provide dummy values for all arguments' types, while now it "just works". We could make the codegen collect all the argument types and populate dummies where possible, but that still won't cover 100% of cases...
3. This shouldn't be needed, since codegen takes care to make all arguments nullable, so `null` would fit everywhere and you won't normally see the "wrong_argument_type" error you mentioned. That being said, there always could be bugs, so codegen could "forget" to override something. If you bumped into that, could you please answer Sam's questions from the previous comment? Thanks!

**Comment by XilaiZhang** [comment]
Umm I hit something similar when trying to do something like
```
      when(
        branchService.getReleaseBranches(
          githubService: anyNamed(githubService),//GithubService(github),
          slug: Config.flutterSlug,
        ),
      ).thenAnswer((Invocation invocation) {
         blah
      });
```
where I would like to use any to match a parameter of the type `GithubService`, but I couldn't because it is not nullable.

**Comment by srawlins** [comment]
The parameter type needs to be nullable. The best way to make the parameter type nullable is to generate the mock with [`@GenerateNiceMocks`](https://pub.dev/packages/mockito#lets-create-mocks).

**Comment by XilaiZhang** [comment]
Umm I might be wrong, is `@GenerateNiceMocks(<MockSpec<dynamic>>[MockSpec(mixingIn: <Type>[GithubService])])` the right way to generate nice mocks?

**Comment by XilaiZhang** [comment]
Umm it seems like after generating with `@GenerateNiceMocks`, the `any` type still can't match a non nullable parameter. yeah maybe the parameter type really has to be nullable

**Comment by srawlins** [comment]
What is the static type of the mock target? Is `branchService` declared as a mock? E.g. `Foo mockFoo = MockFoo()` has a static type of `Foo`, not `MockFoo`.

In the future, questions like this are better suited to a user forum like StackOverflow, with a community of users to help.

**Comment by XilaiZhang** [comment]
Cool I will do more research and ask on stackoverflow instead.

**Comment by yanok** [comment]
Closing: we can't make `any` generic.
