### ISSUE TITLE
Mocking final classes?

### ISSUE THREAD

**Issue by slaci** [dart-lang/mockito#635]
Hello,

Dart 3 introduced some class modifiers, like `final`. A class marked with `final` cannot be extended and mocks are basically created by extending a class. So currently I get the following error when trying to mock a final class:

> Error: The class 'ClassName' can't be implemented outside of its library because it's a final class.

In java there is a package called [mockito-inline](https://www.davidvlijmincx.com/posts/mockito_mock_final_methods_and_classes/) which somehow solves mocking final classes (don't know how).

So my question:
Do anyone see a way to make it possible to mock final classes in dart mockito?

How I ran into this: A plugin author marked some of the plugin's classes final which I previously mocked for tests. So I guess its not a good idea to mark plugin classes final, right?

**Comment by srawlins** [comment]
We cannot support mocking a final class. 

> Do anyone see a way to make it possible to mock final classes in dart mockito?

> How I ran into this: A plugin author marked some of the plugin's classes final which I previously mocked for tests. So I guess its not a good idea to mark plugin classes final, right?

Questions like this are better asked at a user forum like StackOverflow or Discord.

**Comment by 781flyingdutchman** [comment]
For those coming across this: consider using the 'interface' modifier instead of 'final' for classes that are visible to package users. It does allow Mockito to mock it, and it still prevents the class from being extended (which is usually the bigger concern for package developers).

**Comment by gdutpxz** [comment]
> For those coming across this: consider using the 'interface' modifier instead of 'final' for classes that are visible to p

but most sense we use mock for a 3rd lib...

**Comment by yanok** [comment]
Yes, you can't mock `final` classes (or `base` or `sealed`).

The thing is, if you own this class, it's your call, you can either remove `final`, or split it into `interface` that can be mocked and `final` implementation. (you can even make your `interface` `@visibleForTesting` if you want to emphasize it's not there for production use).

If you don't own your class, it's a bit trickier. You can create your wrapper class that contains the class you want to mock and just passes all requests to it. Then you can mock this wrapper class. Of course, for this to be useful, you would have to rewrite all your code to use your wrapper, instead of using the original class directly. Unfortunately that's the only way, if original class' authors are not willing to make a mockable interface.

**Comment by slaci** [comment]
Just to summarize, there are 2 options for this:

- Ask the plugin author to replace `final` by `interface` or just remove `final`. Check [class modifiers](https://dart.dev/language/class-modifiers) doc.
- If the above is not an option, then the only way is to wrap the plugin's class in a wrapper class which you can mock, and use that everywhere.
