### ISSUE TITLE
Generated Imports use Unescaped backslashes

### ISSUE THREAD

**Issue by centmeteenvin** [dart-lang/mockito#711]
When generating a mock of a class that imports from the other class .

`test.dart`
```
import '../bin/webhook.dart';

@GenerateNiceMocks([MockSpec<WebHookService>()])
import "test.mocks.dart";
```
`test.mocks.dart`
```
// Mocks generated by Mockito 5.4.2 from annotations
// in cd/test/server_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;

import '..\bin\models\webhook_payload\webhook_payload.dart' as _i3;
import '..\bin\webhook.dart' as _i2;
```

The last 2 import statements use the backslash. This escapes the firstfollowing charachter making the import unusable.

**Comment by srawlins** [comment]
Great bug report! Can you mention what version of mockito you are running? Thanks!

**Comment by centmeteenvin** [comment]
The latest version 5.4.2.
I did use a lot of other build_runner packages.
What also might be useful is:
Platform Windows.
Dart SDK version 3.15
No flutter
Coding in vscode but not using any of the build_runner extensions.

**Comment by Sese-Schneider** [comment]
I can reproduce this issue and am also impacted by this. cc @srawlins 
I'm unable to generate any mocks.

## Details

### Environment

- Only happens when running `build_runner` on **Windows**
- `mockito: ^5.4.3`
- `build_runner: ^2.4.6`

### Example

This simple file can always reproduce the issue.

```dart
import 'package:mockito/annotations.dart';

import '../u_folder_name/helper.dart';
import 'test.mocks.dart';

@GenerateMocks([Helper])
class Test {}
```

### Stacktrace

I initially had this issue because my folder starts with `u`, and `\u` has a special treatment on windows.

```
[SEVERE] mockito:mockBuilder on test/test.dart (cached):

Could not format because the source could not be parsed:

line 10, column 11 of .: An escape sequence starting with '\u' must be followed by 4 hexadecimal digits.
   ╷
10 │ import '..\u_folder_name\helper.dart' as _i2;
```

### Workarounds

None known yet.
