### ISSUE TITLE
argThat(...) doesn't work in stricter strong mode

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/mockito#80]
... i.e. `implicit-casts: false` and `implicit-dynamic: false`.

```dart
/// An argument matcher that matches an argument that matches [matcher].
argThat(Matcher matcher) => new ArgMatcher(matcher, false);
```

But `typed` expects a `ArgMatcher`. The above returns `dynamic`.

Is this fixable? Or should we just basically wait for a future codegen-based mockito?

**Comment by matanlurey** [comment]
@TedSander tried to type this `ArgMatcher` internally - there are some tests that still use Dart 1.x semantics internally that fail with this change, but it looks like Dart 2.x works fine. We'll hold off on changing this for a little bit.

**Comment by TedSander** [comment]
Note this also applies to any, captureThat, and captureAny. Possibly some others.

**Comment by TedSander** [comment]
So currently this breaks about 8% of tests using mockito internally. We would need to clean that up first.

**Comment by srawlins** [comment]
I do intend to make Mockito a 2.0-semantics-only package soon, so that `typed()` is `@deprecated` and a no-op, and `any` and `argThat` do what `typed` does today. I'll send a PR this week maybe...

We'll have some cleanup because the new semantics will not allow `null` next to `any` any `argThat` arguments, which is a restriction on `typed` right now. (i.e. It's a breaking change.)

**Comment by srawlins** [comment]
OK these signatures have changed, and all the `any|argThat|captureAny|anyNamed|...` API is typed to return Null. I've played around with `--no-implicit-casts` and `--no-implicit-dynamic`, and I think Mockito's API should play well.
